server {
    listen 80;
    server_name api.darshan-pr.tech;

    return 301 https://$host$request_uri;
}

server {

    listen 80;
    server_name api.darshan-pr.tech;

    location / {

        proxy_pass http://frontend;
    }

    location /api/ {

        proxy_pass http://backend:8000/;
    }
}